### ISSUE TITLE
updating with this package

### ISSUE THREAD

**Issue by chrisbbreuer** [Froiden/laravel-installer#5]
Hi!

Do you have any intentions on implementing this?

Thanks :-)

**Comment by ajayfroiden** [comment]
Hi @Chinese1904 ,
Sorry, i did not get your question. Where do you want this to be implemented?

**Comment by chrisbbreuer** [comment]
Thanks for your quick reply. I was just wondering if you will enable a updating method:

`Update: In order to update your application, go to the /update url and follow the instructions.`

There currently isn't an update route. Just wondering 👍

**Comment by NickRT91** [comment]
This would be awesome if implemented :)

**Comment by hyvikk** [comment]
how can i redirect from install to main page if it's already installed?

**Comment by ajayfroiden** [comment]
@hyvikk You do not need to open the /install in that case.

**Comment by chrisbbreuer** [comment]
what I have done in my case is actually redirect if /install is called after it is installed, because visitors are not supposed to see that site. :-)

**Comment by ajayfroiden** [comment]
@Chinese1904 Perfect. Make Sense

**Comment by NickRT91** [comment]
@Chinese1904 Can you share your redirect fix / maybe offer to pull it into here for us others to use? :)

**Comment by chrisbbreuer** [comment]
There are a lot of options actually and it will depend on what you want to achieve. Right now there seems to be a bug, because it should throw a 404 error if it already is installed and the installed routes get accessed, but it does not.

The easiest way is to modify the `routes.php` file like this while the bug hasn't been fixed:

```php
if (! File::exists(storage_path('installed'))) {
    // all the installer routes here
    Route::get('/', [
        'as' => 'welcome',
        'uses' => 'WelcomeController@welcome'
    ]);
    ...
} else {
    abort(404); // or redirect anywhere else
}
```

Make sure to not delete the `installed` file.

If I find some more time, I will look for the bug later. :-)


edit:
please try this PR https://github.com/Froiden/laravel-installer/pull/8
