### ISSUE TITLE
Routes not working?!

### ISSUE THREAD

**Issue by webdesign3r** [Froiden/laravel-installer#7]
Hi,

I installed your package, uploaded everything to my server, but when i try to go to the /install page, it says

The requested URL /install was not found on this server.

What am I doing wrong? I did all the steps from the readme, but my routes/web.php has no entry for /install 

I think the artisan vendor:publish did not publish all files needed?
`php artisan vendor:publish --provider="Froiden\LaravelInstaller\Providers\LaravelInstallerServiceProvider"
Copied File [\vendor\froiden\laravel-installer\src\Config\installer.php] To [\config\installer.php]
Copied Directory [\vendor\froiden\laravel-installer\src\assets] To [\public\installer]
Copied Directory [\vendor\froiden\laravel-installer\src\Views] To [\resources\views\vendor\installer]
Copied Directory [\vendor\froiden\laravel-installer\src\Lang] To [\resources\lang]
`

**Comment by chrisbbreuer** [comment]
did you register the service provider?

**Comment by webdesign3r** [comment]
I did, its working on my local computer, but not after uploading via ftp

**Comment by chrisbbreuer** [comment]
are the vendor files in there? Laravel permissions set correctly? Are display_errors set to on in php.ini? What's the error?

**Comment by webdesign3r** [comment]
Hey again

The vendor files are there, yes, but I can't access any of the routes defined in /vendor/froiden/laravel-installer/src/routes.php

When I go to the site, I can see the basic html of my index, but without any css styling etc..
http://test.ferienhaus-holzer.at is the domain.. when I try http://test.ferienhaus-holzer.at/install the only error I get is 

> The requested URL /install was not found on this server.
> Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by ajayfroiden** [comment]
@webdesign3r Which version of Laravel you are using? and Does `vendor:publish` worked?

**Comment by webdesign3r** [comment]
@ajayfroiden I am using 5.4

I did run
`php artisan vendor:publish --provider="Froiden\LaravelInstaller\Providers\LaravelInstallerServiceProvider"`
as its said in the readme, and it didnt throw any errors.. in my original post you can see the output i got in the console
